#ifndef RGB30_CONTROLLER_H
#define RGB30_CONTROLLER_H

#include <stdbool.h>
#include <raylib.h>

enum rgb30_buttons {
    RGB30_BUTTON_UNKNOWN = -1,
    RGB30_BUTTON_RIGHT_FACE_DOWN,
    RGB30_BUTTON_RIGHT_FACE_RIGHT,
    RGB30_BUTTON_RIGHT_FACE_UP,
    RGB30_BUTTON_RIGHT_FACE_LEFT,
    RGB30_BUTTON_LEFT_TRIGGER_1,
    RGB30_BUTTON_RIGHT_TRIGGER_1,
    RGB30_BUTTON_LEFT_TRIGGER_2,
    RGB30_BUTTON_RIGHT_TRIGGER_2,
    RGB30_BUTTON_MIDDLE_LEFT,
    RGB30_BUTTON_MIDDLE_RIGHT,
    _UNUSED_MIDDLE_BUTTON,
    RGB30_BUTTON_LEFT_THUMB,
    RGB30_BUTTON_RIGHT_THUMB,
    RGB30_BUTTON_LEFT_FACE_UP,
    RGB30_BUTTON_LEFT_FACE_DOWN,
    RGB30_BUTTON_LEFT_FACE_LEFT,
    RGB30_BUTTON_LEFT_FACE_RIGHT,
    RGB30_BUTTON_COUNT
};

static char rgb30_button_names[17][8] = {
    [RGB30_BUTTON_RIGHT_FACE_DOWN] = "B",
    [RGB30_BUTTON_RIGHT_FACE_RIGHT] = "A",
    [RGB30_BUTTON_RIGHT_FACE_UP] = "X",
    [RGB30_BUTTON_RIGHT_FACE_LEFT] = "Y",
    [RGB30_BUTTON_LEFT_TRIGGER_1] = "L1",
    [RGB30_BUTTON_RIGHT_TRIGGER_1] = "R1",
    [RGB30_BUTTON_LEFT_TRIGGER_2] = "L2",
    [RGB30_BUTTON_RIGHT_TRIGGER_2] = "R2",
    [RGB30_BUTTON_MIDDLE_LEFT] = "SELECT",
    [RGB30_BUTTON_MIDDLE_RIGHT] = "START",
    [_UNUSED_MIDDLE_BUTTON] = "UNUSED",
    [RGB30_BUTTON_LEFT_THUMB] = "L3",
    [RGB30_BUTTON_RIGHT_THUMB] = "R3",
    [RGB30_BUTTON_LEFT_FACE_UP] = "D-UP",
    [RGB30_BUTTON_LEFT_FACE_DOWN] = "D-DOWN",
    [RGB30_BUTTON_LEFT_FACE_LEFT] = "D-LEFT",
    [RGB30_BUTTON_LEFT_FACE_RIGHT] = "D-RIGHT",
};

static int prev_button_state[RGB30_BUTTON_COUNT] = {0};
static int button_state[RGB30_BUTTON_COUNT] = {0};
static int last_button_pressed = RGB30_BUTTON_UNKNOWN;

bool is_button_pressed(int button);
void update_button_state(void);
void refresh_button_state(void);

#endif // RGB30_CONTROLLER_H
